version: "3.9"

services:
  bot:
    build:
      context: .
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGODB_LOCAL_URI=${MONGODB_LOCAL_URI}
    restart: always
    env_file:
      - ./.env
    ports:
      - '6000:27017'
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:





